[package]
name = "meme"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
exclude = ["**/*.toml"] 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
# 适度优化，但仍保留调试信息
opt-level = 1          # 基础优化，比0好很多
# 不要开 lto = true，会严重拖慢编译时间

[profile.release]
opt-level = "z"    # 激进优化体积（也可用 "s"）
lto = true         # 开启链接时优化，消除冗余代码
codegen-units = 1  # 优化整个程序，而非按“零件”编译
strip = true       # 移除调试符号，直接减小 so 文件
panic = "abort"    # 简化错误处理逻辑，减小体积

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "meme_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
image = { version = "0.25", default-features = false, features = ["png"] }
pinyin = "0.10"
toml = { version = "0.8", default-features = false, features = ["parse"] }
toml_edit = "0.22"
percent-encoding = "2"
log = "0.4"
base64 = "0.22"

[target.'cfg(not(target_os = "android"))'.dependencies]
clipboard-rs = "0.3"

[target.'cfg(target_os = "android")'.dependencies]
tauri-plugin-share = "2"
tauri-plugin-android-fs = "2"
